### ISSUE TITLE
Adjustments for other locations

### ISSUE THREAD

**Issue by akrueger** [atogle/walkshed.js#4]
I'm trying to get this to work in another part of the country and I wasn't sure if there were some adjustments that could be made in the code to support that.

Thanks

**Comment by atogle** [comment]
Actually, there are several things that would need to be changed. The main hurdle is that this uses a tile set that was generated only for Philadelphia. It's on my to do list to make this less specific, but that's unfortunately a very long to do list. 😕

**Comment by akrueger** [comment]
@atogle how complicated of a change for me to make locally would it be to generate the tileset for a different area? I saw a lat/long in the code:

``` map
    .setView([39.9524, -75.1636], 14)
    .addLayer(layer);
```

Wasn't sure if it was just flipping some bits to change lat/long or there was a lot more involvement hard coded into Philadelphia. I only need Austin, TX, so if a similar sized tile can just be moved over, that would work for me.
